[project]
name = "webapp-blog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastapi[standard]>=0.128.3",
    "greenlet>=3.3.1",
    "psycopg>=3.3.2",
    "sqlalchemy>=2.0.46",
]
